name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - main
      - release-*
    tags-ignore: [ v.* ]

permissions:
  contents: read

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { jvmName: "temurin:1.8.0"  }
          # { jvmName: "temurin:1.11.0" }
          # { jvmName: "temurin:1.17.0" }
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.1

      - name: Set up JDK ${{ matrix.jvmName }}
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: ${{ matrix.jvmName }}

      - name: Intall Jekyll, Nanoc, Asciidoctor, Gitbook
        run: |-
          sudo gem install jekyll:3.8.4 nanoc:4.0.2 asciidoctor --no-document
          npm install -g gitbook-cli@2.3.2
          gitbook install 3.2.3

      - name: sbt test
        run: sbt "^^$SBT_CROSS_VERSION; compile; runScriptedTest; makeSite"
