name: Release
on:
  push:
    branches:
      - main
      - release-*
    tags: ["v*"]

permissions:
  contents: read

jobs:
  release:
    name: Release to Sonatype
    if: github.event.repository.fork == false
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5.7.0
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "sbt"

      - name: Setup sbt
        uses: sbt/setup-sbt@v1.5.7

      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  documentation:
    name: Release Documentation
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: "temurin"
          java-version: "17"
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@8feba82adc7f01ddcf8165b86f778bdb5b82cebc # v1.5.7

      - run: sbt makeSite

      - uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          folder: target/site
        if: ${{ github.repository_owner == 'sbt' }}
